In [166]:
import numpy as np

a = np.array([[1,6], [2,8], [3,11], [3,10], [1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [168]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [170]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [172]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

8.0

In [179]:
result = a_centered_sp / (5 - 1)
result

2.0

Проверка

In [176]:
res = a.T
result = np.cov(res)
result[0,1]

2.0